CREATE TABLE IF NOT EXISTS statistics
(
    statistic_id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    app                 VARCHAR(512)                            NOT NULL,
    uri                 VARCHAR(512)                            NOT NULL,
    ip                  VARCHAR(64)                             NOT NULL,
    timestamp_statistic TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_statistic PRIMARY KEY (statistic_id)
);

