package explore.with.me.categories.repositories;

import explore.with.me.categories.models.Category;
import org.springframework.data.jpa.repository.JpaRepository;

/**
 * интерфейс для работы с БД Категории
 *
 * <p>
 * category_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
 * category_name VARCHAR(50)                             NOT NULL,
 * CONSTRAINT pk_category PRIMARY KEY (category_id),
 * CONSTRAINT uq_category_name UNIQUE (category_name)
 */
public interface CategoryRepository extends JpaRepository<Category, Long> {
}
